/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BlogDetail: typeof import('./src/components/BlogDetail.vue')['default']
    BlogDetali: typeof import('./src/components/BlogDetali.vue')['default']
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    Card_blog: typeof import('./src/components/BlogPost.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PanelAdmin: typeof import('./src/components/PanelAdmin.vue')['default']
    ProductCarousel: typeof import('./src/components/ProductCarousel.vue')['default']
    ProductSection: typeof import('./src/components/ProductSection.vue')['default']
    RegisterDialog: typeof import('./src/components/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Sellos: typeof import('./src/components/Sellos.vue')['default']
    SellosHome: typeof import('./src/components/SellosHome.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
  }
}
