/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    CartDrawer: typeof import('./src/components/CartDrawer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProductSection: typeof import('./src/components/ProductSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Sellos: typeof import('./src/components/Sellos.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
  }
}
