"""Add product fields

Revision ID: 71666aed0365
Revises: 
Create Date: 2025-12-08 20:53:21.085773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71666aed0365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eco_badges', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('materials', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('emissions', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('emissions')
        batch_op.drop_column('origin')
        batch_op.drop_column('materials')
        batch_op.drop_column('eco_badges')
        batch_op.drop_column('rating')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
